timeServer:
  image: ifilyaninitmo/time-server-mega-itmo:main
  port: 8001
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8001

authServer:
  image: ifilyaninitmo/auth-server-mega-itmo:main
  port: 8000
  replicaCount: 1
  service:
    type: NodePort
    port: 8000
    nodePort: 32000
  env:
    MONGODB_CONN_STR: "mongodb://root:SuperSecret123@mongodb-release.mongodb.svc.cluster.local:27017/auth?authSource=admin"
    TIMESERVER_URL: "http://time-server:8001"
