apiVersion: v1
kind: Service
metadata:
  name: time-server
spec:
  type: {{ .Values.timeServer.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.timeServer.service.port }}
    targetPort: {{ .Values.timeServer.port }}
  selector:
    app: time-server
