apiVersion: v1
kind: Service
metadata:
  name: time-server
spec:
  selector:
      app: time-server
  ports: 
    - protocol: TCP
      port: {{ .Values.timeServer.port }}
      targetPort: {{ .Values.timeServer.port }}

