name: Helm Lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  helm-lint:
    name: Helm Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download dependencies MyService
        run: |
          helm dependency build charts/myservice

      - name: helm-check MyService
        uses: igabaydulin/helm-check-action@0.2.1
        env:
          CHART_LOCATION: charts/myservice
          CHART_VALUES: charts/myservice/values.yaml

